apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.environment}}-sample-stateless-service
  #namespace: sample-stateless-service
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.environment}}-sample-stateless-service
    spec:
      containers:
      - name: sample-stateless-service
        image: -your-registry-/sample-stateless-service:{{.tag}}
        env:
        - name: CLASSPATH
          value: .:/etc/secrets/*:/app/*.jar
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "2Gi"
        ports:
        - containerPort: 8080
