kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.environment}}-kubeam-mysql-pvc
  namespace: {{.environment}}-kubeam
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 100Gi
