apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.environment}}-kubeam-redis
  name: {{.environment}}-kubeam-redis
spec:
  ports:
    # The port that this service should serve on.
    - port: 6379
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: {{.environment}}-kubeam-redis
  type: NodePort
