version: '3'
services:
  redis:
    image: redis
    ports:
    - "6000:6379"
  mariadb:
    image: mariadb:10
    ports:
    - "5000:3306"
    volumes:
    - /tmp/mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=kubeam
  kubeam:
    image: kubeam
    ports:
    - "8443:443"
    build:
      context: ~/kubeAM/
      dockerfile: Dockerfile-kubeam.dkr