kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zalenium-videos-{{.environment}}-pvc
  namespace: test-framework
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
