apiVersion: v1
kind: Service
metadata:
  labels:
    app: zalenium-{{.environment}}
  name: zalenium-{{.environment}}-service
spec:
  ports:
  - name: zalenium
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: zalenium-{{.environment}}
    role: grid
  type: NodePort
