kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-mysql-pvc
  namespace: sample
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
