apiVersion: v1
kind: Service
metadata:
  name: sample-mysql-service
  #namespace: sample
  #labels:
  #  run: myproject
spec:
  selector:
    app: sample-mysql
  ports:
    - name: mysql
      port: 3306 
      targetPort: 3306
      protocol: TCP
  type: NodePort
