apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.application}}-deployment
  namespace: {{.environment}}-{{.application}}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 90%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.environment}}-{{.application}}
    spec:
      containers:
      - name: {{.application}}
        image: localhost:5000/{{.application}}:{{.tag}}
        env:
        - name: CLASSPATH
          value: .:/etc/secrets/*:/app/*.jar
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 8080
